Logistic Regression


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn


In [ ]:
dataset=pd.read_csv('framingham.csv')
dataset

male  age  education  currentSmoker  cigsPerDay  BPMeds  \
0        1   39        4.0              0         0.0     0.0   
1        0   46        2.0              0         0.0     0.0   
2        1   48        1.0              1        20.0     0.0   
3        0   61        3.0              1        30.0     0.0   
4        0   46        3.0              1        23.0     0.0   
...    ...  ...        ...            ...         ...     ...   
4233     1   50        1.0              1         1.0     0.0   
4234     1   51        3.0              1        43.0     0.0   
4235     0   48        2.0              1        20.0     NaN   
4236     0   44        1.0              1        15.0     0.0   
4237     0   52        2.0              0         0.0     0.0   

      prevalentStroke  prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  \
0                   0             0         0    195.0  106.0   70.0  26.97   
1                   0             0         0    250.0  121.0   81.0  28.73   
2                   0             0         0    245.0  127.5   80.0  25.34   
3                   0             1         0    225.0  150.0   95.0  28.58   
4                   0             0         0    285.0  130.0   84.0  23.10   
...               ...           ...       ...      ...    ...    ...    ...   
4233                0             1         0    313.0  179.0   92.0  25.97   
4234                0             0         0    207.0  126.5   80.0  19.71   
4235                0             0         0    248.0  131.0   72.0  22.00   
4236                0             0         0    210.0  126.5   87.0  19.16   
4237                0             0         0    269.0  133.5   83.0  21.47   

      heartRate  glucose  TenYearCHD  
0          80.0     77.0           0  
1          95.0     76.0           0  
2          75.0     70.0           0  
3          65.0    103.0           1  
4          85.0     85.0           0  
...         ...      ...         ...  
4233       66.0     86.0           1  
4234       65.0     68.0           0  
4235       84.0     86.0           0  
4236       86.0      NaN           0  
4237       80.0    107.0           0  

[4238 rows x 16 columns]

In [ ]:
dataset.drop(dataset.columns[[0,5,7,8,9,10,11,12,13,14,15]],axis=1,inplace=True)

In [ ]:
dataset.head(5)

age  education  currentSmoker  cigsPerDay  prevalentStroke
0   39        4.0              0         0.0                0
1   46        2.0              0         0.0                0
2   48        1.0              1        20.0                0
3   61        3.0              1        30.0                0
4   46        3.0              1        23.0                0

In [ ]:
dataset.isnull().sum()

age                  0
education          105
currentSmoker        0
cigsPerDay          29
prevalentStroke      0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imp=SimpleImputer(strategy="mean")
dataset['education']=imp.fit_transform(dataset[['education']])
dataset['cigsPerDay']=imp.fit_transform(dataset[['cigsPerDay']])
dataset.isnull().sum()


age                0
education          0
currentSmoker      0
cigsPerDay         0
prevalentStroke    0
dtype: int64

Creating feature matrix and dependent variable vector


In [ ]:
x=dataset.iloc[:,2:4].values
y=dataset.iloc[:,4].values


Feature Matrix

In [ ]:
x

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 1., 20.],
       ...,
       [ 1., 20.],
       [ 1., 15.],
       [ 0.,  0.]])

Dependent Variable

In [ ]:
y

array([0, 0, 0, ..., 0, 0, 0])

Splitting data into training data and test data

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
x_train.shape

(2966, 2)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


Training the model

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)

LogisticRegression(random_state=0)

Prediction

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[1268,    0],
       [   4,    0]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9968553459119497